<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /dede/uploads/allimg/171023/1-1G023112035.jpg ",93,248);
$z[1][4]['ddimg']="/dede/uploads/allimg/171023/1-1G023112035.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="440";
$z[1][4]['height']="436";
$z[2]=Array("img"," /dede/uploads/allimg/171023/1-1G023112035.gif ",250,405);
$z[2][4]['ddimg']="/dede/uploads/allimg/171023/1-1G023112035.gif";
$z[2][4]['text']="";
$z[2][4]['width']="220";
$z[2][4]['height']="220";
$z[3]=Array("img"," /dede/uploads/allimg/171023/1-1G023112035-50.jpg ",407,568);
$z[3][4]['ddimg']="/dede/uploads/allimg/171023/1-1G023112035-50.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="440";
$z[3][4]['height']="303";
$z[4]=Array("img"," /dede/uploads/allimg/171023/1-1G023112035-51.jpg ",570,731);
$z[4][4]['ddimg']="/dede/uploads/allimg/171023/1-1G023112035-51.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="440";
$z[4][4]['height']="303";
$z[5]=Array("img"," /dede/uploads/allimg/171023/1-1G023112035-52.jpg ",733,894);
$z[5][4]['ddimg']="/dede/uploads/allimg/171023/1-1G023112035-52.jpg";
$z[5][4]['text']="";
$z[5][4]['width']="550";
$z[5][4]['height']="550";

?>