<?php
$z[0]=Array("field","",1692,1722);
$z[0][4]['name']="typename";
$z[1]=Array("field","",1776,1806);
$z[1][4]['name']="position";
$z[2]=Array("field","",1851,1878);
$z[2][4]['name']="title";
$z[3]=Array("field","",1928,1992);
$z[3][4]['name']="pubdate";
$z[3][4]['function']="strftime(\"%Y-%m-%d\",@me)";
$z[4]=Array("field","",2045,2071);
$z[4][4]['name']="body";
$z[5]=Array("arclist","\r\n					<li><a href=\"[field:arcurl /]\" target=\"_blank\">【[field:typename /]】[field:title /]</a></li>\r\n				",2352,2541);
$z[5][4]['typeid']="3";
$z[5][4]['getall']="1";
$z[5][4]['orderby']="pubdate";
$z[5][4]['limit']="0,6";
$z[6]=Array("arclist","\r\n				<div class=\"art_pic art_pic1\"><a href=\"[field:arcurl]\" target='_blank'><img width='318' height='148' src=\"[field:litpic /]\" /></a></div>\r\n			",2565,2783);
$z[6][4]['typeid']="35";
$z[6][4]['orderby']="pubdate";
$z[6][4]['limit']="0,1";
$z[7]=Array("arclist","\r\n				<div class=\"art_pic art_pic2\"><a href=\"[field:arcurl]\" target='_blank'><img width='318' height='170' src=\"[field:litpic /]\" /></a></div>\r\n			",2788,3006);
$z[7][4]['typeid']="35";
$z[7][4]['orderby']="pubdate";
$z[7][4]['limit']="1,1";
$z[8]=Array("arclist","\r\n				<div class=\"art_pic art_pic3\"><a href=\"[field:arcurl]\" target='_blank'><img width='318' height='143' src=\"[field:litpic /]\" /></a></div>\r\n			",3011,3229);
$z[8][4]['typeid']="35";
$z[8][4]['orderby']="pubdate";
$z[8][4]['limit']="2,1";

?>