<?php
$z[0]=Array("field","",1699,1729);
$z[0][4]['name']="typename";
$z[1]=Array("field","",2004,2034);
$z[1][4]['name']="position";
$z[2]=Array("list","\r\n                <li>\r\n                    <h2><a href=\"[field:arcurl /]\" target=\"_blank\">【[field:typename /]】[field:title /]</a></h2>\r\n                    <p>[field:description /]<i>[field:pubdate function=\"strftime('%m-%d',@me)\" /]</i></p>\r\n                </li>\r\n                ",2118,2476);
$z[2][4]['orderby']="pubdate";
$z[2][4]['pagesize']="10";
$z[2][4]['orderway']="desc";
$z[3]=Array("pagelist","",2546,2612);
$z[3][4]['listsize']="5";
$z[3][4]['listitem']="index,pre,pageno,next,end";

?>