<li>
                    <a href="[field:arcurl /]" target="_blank" class="pica">
                        <!--<i></i>-->
                        <!--<code></code>-->
                        <img width="242" height="148" src="[field:litpic function='str_replace("ledou/uploads","uploads",@me)'/]" />
                    </a>
                    <p><a href="[field:arcurl /]" target="_blank">[field:title /]</a></p>
                </li>