<?php
$z[0]=Array("field","",39,128);
$z[0][4]['name']="typeid";
$z[0][4]['function']="getTypeConfig(@me,'扫一扫下载游戏二维码图片')";
$z[1]=Array("field","",166,234);
$z[1][4]['name']="typeid";
$z[1][4]['function']="getTypeConfig(@me,'ios下载地址')";
$z[2]=Array("field","",268,339);
$z[2][4]['name']="typeid";
$z[2][4]['function']="getTypeConfig(@me,'安卓下载地址')";
$z[3]=Array("field","",392,457);
$z[3][4]['name']="typeid";
$z[3][4]['function']="getTypeConfig(@me,'客服电话')";
$z[4]=Array("field","",494,558);
$z[4][4]['name']="typeid";
$z[4][4]['function']="getTypeConfig(@me,'玩家QQ群')";

?>