<?php
$z[0]=Array("field","",387,410);
$z[0][4]['name']="seotitle";
$z[1]=Array("field","",489,512);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",620,646);
$z[2][4]['name']="description";
$z[3]=Array("type","[field:siteurl /]",810,850);
$z[4]=Array("field","",1028,1082);
$z[4][4]['name']="typeid";
$z[4][4]['function']="GetParentTypename(@me)";
$z[5]=Array("include","",1086,1142);
$z[5][4]['filename']="ledou/commom_paihangbang.html";
$z[6]=Array("include","",1198,1246);
$z[6][4]['filename']="ledou/commom_top.html";
$z[7]=Array("include","",1320,1370);
$z[7][4]['filename']="ledou/commom_video.html";
$z[8]=Array("field","",1462,1492);
$z[8][4]['name']="typename";
$z[9]=Array("field","",1546,1576);
$z[9][4]['name']="position";
$z[10]=Array("list","\r\n                <li>\r\n                    <a href=\"[field:arcurl /]\" target=\"_blank\" class=\"pica\">\r\n                        <!--<i></i>-->\r\n                        <!--<code></code>-->\r\n                        <img width=\"242\" height=\"148\" src=\"[field:litpic function='str_replace(\"ledou/uploads\",\"uploads\",@me)'/]\" />\r\n                    </a>\r\n                    <p><a href=\"[field:arcurl /]\" target=\"_blank\">[field:title /]</a></p>\r\n                </li>\r\n                ",1707,2255);
$z[10][4]['orderby']="pubdate";
$z[10][4]['pagesize']="9";
$z[10][4]['orderway']="desc";
$z[11]=Array("field","",2314,2341);
$z[11][4]['name']="typeid";
$z[12]=Array("pagelist","",2480,2497);
$z[13]=Array("include","",2552,2604);
$z[13][4]['filename']="ledou/commom_erweima.html";
$z[14]=Array("include","",2618,2671);
$z[14][4]['filename']="ledou/commom_rightarc.html";
$z[15]=Array("include","",2732,2783);
$z[15][4]['filename']="ledou/commom_footer.html";
$z[16]=Array("include","",2800,2853);
$z[16][4]['filename']="ledou/commom_rightNav.html";
$z[17]=Array("type","[field:siteurl /]",2894,2934);

?>