<?php
$z[0]=Array("field","",1695,1725);
$z[0][4]['name']="typename";
$z[1]=Array("field","",1779,1809);
$z[1][4]['name']="position";
$z[2]=Array("field","",1854,1881);
$z[2][4]['name']="title";
$z[3]=Array("field","",1931,1996);
$z[3][4]['name']="pubdate";
$z[3][4]['function']="strftime('%Y-%m-%d',@me)";
$z[4]=Array("field","",3015,3062);
$z[4][4]['name']="imgurls";
$z[4][4]['alt']="点击翻页";
$z[5]=Array("pagebreak","",3572,3590);

?>