<?php
$z[0]=Array("field","",1695,1725);
$z[0][4]['name']="typename";
$z[1]=Array("field","",1779,1809);
$z[1][4]['name']="position";
$z[2]=Array("list","\r\n                <li>\r\n                    <a href=\"[field:arcurl /]\" target=\"_blank\" class=\"pica\">\r\n                        <i></i>\r\n                        <code></code>\r\n                        <img width=\"242\" height=\"148\" src=\"[field:litpic /]\" />\r\n                    </a>\r\n                    <p><a href=\"[field:arcurl /]\" target=\"_blank\">[field:title /]</a></p>\r\n                </li>\r\n                ",1896,2377);
$z[2][4]['orderby']="pubdate";
$z[2][4]['pagesize']="1";
$z[2][4]['orderway']="desc";
$z[3]=Array("field","",2436,2463);
$z[3][4]['name']="typeid";
$z[4]=Array("pagelist","",2586,2603);

?>