<?php
$z[0]=Array("arclist","\r\n  <li><a href=\"[field:arcurl /]\" target=\"_blank\">【[field:typename /]】[field:title /]</a></li>\r\n  ",107,291);
$z[0][4]['typeid']="3";
$z[0][4]['getall']="1";
$z[0][4]['orderby']="pubdate";
$z[0][4]['limit']="0,6";
$z[1]=Array("arclist","\r\n<div class=\"art_pic art_pic1\"><a href=\"[field:arcurl]\" target='_blank'><img width='318' height='148' src=\"[field:litpic /]\" /></a></div>\r\n",300,511);
$z[1][4]['typeid']="35";
$z[1][4]['orderby']="pubdate";
$z[1][4]['limit']="0,1";
$z[2]=Array("arclist","\r\n<div class=\"art_pic art_pic2\"><a href=\"[field:arcurl]\" target='_blank'><img width='318' height='170' src=\"[field:litpic /]\" /></a></div>\r\n",513,724);
$z[2][4]['typeid']="35";
$z[2][4]['orderby']="pubdate";
$z[2][4]['limit']="1,1";
$z[3]=Array("arclist","\r\n<div class=\"art_pic art_pic3\"><a href=\"[field:arcurl]\" target='_blank'><img width='318' height='143' src=\"[field:litpic /]\" /></a></div>\r\n",726,937);
$z[3][4]['typeid']="35";
$z[3][4]['orderby']="pubdate";
$z[3][4]['limit']="2,1";

?>