<?php
$z[0]=Array("field","",1697,1727);
$z[0][4]['name']="typename";
$z[1]=Array("field","",1781,1811);
$z[1][4]['name']="position";
$z[2]=Array("list","\r\n                <li>\r\n                    <a href=\"[field:arcurl /]\" target=\"_blank\" class=\"pica\">\r\n                        <i></i>\r\n                        <code></code>\r\n                        <img width=\"242\" height=\"148\" src=\"[field:litpic /]\" />\r\n                    </a>\r\n                    <p><a href=\"[field:arcurl /]\" target=\"_blank\">[field:title /]</a></p>\r\n                </li>\r\n                ",3134,3615);
$z[2][4]['orderby']="pubdate";
$z[2][4]['pagesize']="9";
$z[2][4]['orderway']="desc";
$z[3]=Array("pagelist","",4094,4160);
$z[3][4]['listsize']="5";
$z[3][4]['listitem']="index,pre,pageno,next,end";

?>