<div class="Topbar">
	<div class="main">
    	<div class="logo-ledou lt"><a href="#" target="_blank" title=""></a></div>
		<div class="hotplay_pic lt">
			<img src="/1710files/images/hotplay.jpg">
		</div>
		<div class="play_stroy rt">
			乐逗游戏商城
		</div>
		<div class="play_rank rt">
			乐逗游戏排行榜
            <div class="ost_rank">
                <!-- new game -->
                <div class="ost_rank_col" id="rank_control1">
                    <div class="col-head">
                        <h2 class="rank-title">新游排行榜</h2>
                        <a href="#" target="_blank" class="rank-more">更多<i class="icon-font">?</i></a>
                    </div>
                    <div class="col-body">
                        <ul class="rank-list">
                            <li class="rank-head"><span class="rank-order-hd">排名</span><span class="rank-name-hd">游戏</span></li>
                            <li class="rank-item">
                                <span class="rank-order-color">1</span>
                                <div class="rank-name-game cover-tip">
                                    <a class="ctip-text" href="#" target="_blank">冒险岛2</a>
                                    <div class="rank-game-cover cover-bottom" style="">
                                        <img class="game-img" src="/1710files/images/mxd2-2.jpg" width="194" height="82" alt="">
                                        <p class="game-meta"><a href="#" target="_blank" class="game-link"><i class="icon-home"></i>进入官网</a><a href="#" target="_blank" class="game-link"><i class="icon-download"></i>下载游戏</a></p>
                                    </div>
                                </div>
                            </li>
                            <li class="rank-item current">
                                <span class="rank-order-color">2</span>
                                <div class="rank-name-game cover-tip">
                                    <a class="ctip-text" href="#" target="_blank">冒险岛2</a>
                                    <div class="rank-game-cover cover-bottom" style="">
                                        <img class="game-img" src="/1710files/images/mxd2-2.jpg" width="194" height="82" alt="">
                                        <p class="game-meta"><a href="#" target="_blank" class="game-link"><i class="icon-home"></i>进入官网</a><a href="#" target="_blank" class="game-link"><i class="icon-download"></i>下载游戏</a></p>
                                    </div>
                                </div>
                            </li>
                            <li class="rank-item">
                                <span class="rank-order-color">3</span>
                                <div class="rank-name-game cover-tip">
                                    <a class="ctip-text" href="#" target="_blank">冒险岛2</a>
                                    <div class="rank-game-cover cover-bottom" style="">
                                        <img class="game-img" src="/1710files/images/mxd2-2.jpg" width="194" height="82" alt="">
                                        <p class="game-meta"><a href="#" target="_blank" class="game-link"><i class="icon-home"></i>进入官网</a><a href="#" target="_blank" class="game-link"><i class="icon-download"></i>下载游戏</a></p>
                                    </div>
                                </div>
                            </li>
                            <li class="rank-item">
                                <span class="rank-order-gray">4</span>
                                <div class="rank-name-game cover-tip">
                                    <a class="ctip-text" href="#" target="_blank">冒险岛2</a>
                                    <div class="rank-game-cover cover-bottom" style="">
                                        <img class="game-img" src="/1710files/images/mxd2-2.jpg" width="194" height="82" alt="">
                                        <p class="game-meta"><a href="#" target="_blank" class="game-link"><i class="icon-home"></i>进入官网</a><a href="#" target="_blank" class="game-link"><i class="icon-download"></i>下载游戏</a></p>
                                    </div>
                                </div>
                            </li>
                            <li class="rank-item">
                                <span class="rank-order-gray">5</span>
                                <div class="rank-name-game cover-tip">
                                    <a class="ctip-text" href="#" target="_blank">冒险岛2</a>
                                    <div class="rank-game-cover cover-bottom" style="">
                                        <img class="game-img" src="/1710files/images/mxd2-2.jpg" width="194" height="82" alt="">
                                        <p class="game-meta"><a href="#" target="_blank" class="game-link"><i class="icon-home"></i>进入官网</a><a href="#" target="_blank" class="game-link"><i class="icon-download"></i>下载游戏</a></p>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
                <!-- hot game -->
                <div class="ost_rank_col" id="rank_control2">
                    <div class="col-head">
                        <h2 class="rank-title">热门排行榜</h2>
                        <a href="http://ossweb-img.qq.com/images/js/topfiles/ost1410/gmap.htm" target="_blank" class="rank-more" onclick="pgvSendClick({hottag:'gamerank.hot.more'})">更多<i class="icon-font">?</i></a>
                    </div>
                    <div class="col-body">
                        <ul class="rank-list">
                            <li class="rank-head"><span class="rank-order-hd">排名</span><span class="rank-name-hd">游戏</span></li>
                            <li class="rank-item current">
                                <span class="rank-order-color">1</span>
                                <div class="rank-name-game cover-tip">
                                    <a class="ctip-text" href="#" target="_blank">冒险岛2</a>
                                    <div class="rank-game-cover cover-bottom" style="">
                                        <img class="game-img" src="/1710files/images/mxd2-2.jpg" width="194" height="82" alt="">
                                        <p class="game-meta"><a href="#" target="_blank" class="game-link"><i class="icon-home"></i>进入官网</a><a href="#" target="_blank" class="game-link"><i class="icon-download"></i>下载游戏</a></p>
                                    </div>
                                </div>
                            </li>
                            <li class="rank-item">
                                <span class="rank-order-color">2</span>
                                <div class="rank-name-game cover-tip">
                                    <a class="ctip-text" href="#" target="_blank">冒险岛2</a>
                                    <div class="rank-game-cover cover-bottom" style="">
                                        <img class="game-img" src="/1710files/images/mxd2-2.jpg" width="194" height="82" alt="">
                                        <p class="game-meta"><a href="#" target="_blank" class="game-link"><i class="icon-home"></i>进入官网</a><a href="#" target="_blank" class="game-link"><i class="icon-download"></i>下载游戏</a></p>
                                    </div>
                                </div>
                            </li>
                            <li class="rank-item">
                                <span class="rank-order-color">3</span>
                                <div class="rank-name-game cover-tip">
                                    <a class="ctip-text" href="#" target="_blank">冒险岛2</a>
                                    <div class="rank-game-cover cover-bottom" style="">
                                        <img class="game-img" src="/1710files/images/mxd2-2.jpg" width="194" height="82" alt="">
                                        <p class="game-meta"><a href="#" target="_blank" class="game-link"><i class="icon-home"></i>进入官网</a><a href="#" target="_blank" class="game-link"><i class="icon-download"></i>下载游戏</a></p>
                                    </div>
                                </div>
                            </li>
                            <li class="rank-item">
                                <span class="rank-order-gray">4</span>
                                <div class="rank-name-game cover-tip">
                                    <a class="ctip-text" href="#" target="_blank">冒险岛2</a>
                                    <div class="rank-game-cover cover-bottom" style="">
                                        <img class="game-img" src="/1710files/images/mxd2-2.jpg" width="194" height="82" alt="">
                                        <p class="game-meta"><a href="#" target="_blank" class="game-link"><i class="icon-home"></i>进入官网</a><a href="#" target="_blank" class="game-link"><i class="icon-download"></i>下载游戏</a></p>
                                    </div>
                                </div>
                            </li>
                            <li class="rank-item">
                                <span class="rank-order-gray">4</span>
                                <div class="rank-name-game cover-tip">
                                    <a class="ctip-text" href="#" target="_blank">冒险岛2</a>
                                    <div class="rank-game-cover cover-bottom" style="">
                                        <img class="game-img" src="/1710files/images/mxd2-2.jpg" width="194" height="82" alt="">
                                        <p class="game-meta"><a href="#" target="_blank" class="game-link"><i class="icon-home"></i>进入官网</a><a href="#" target="_blank" class="game-link"><i class="icon-download"></i>下载游戏</a></p>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
		</div>
	</div>
</div>