<div class="fixedTop">
	<div class="main cc">
		<div class="logo lt"><a href="#" target="_blank"><img src="/1710files/images/logo.png" /></a></div>
		<div class="play_sm lt">正版授权    极致还原<br />凡人·不凡</div>
		<ul class="nav rt">
			<li><a href="#" target="_blank">首页</a></li>
			<li><a href="#" target="_blank">资讯</a></li>
			<li><a href="#" target="_blank">门派</a></li>
			<li><a href="#" target="_blank">攻略</a></li>
			<li><a href="#" target="_blank">视频</a></li>
			<li><a href="#" target="_blank">论坛</a></li>
		</ul>
	</div>
</div>
